import{i as a}from"./assets/vendor-I1I71QQ2.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))e(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&e(i)}).observe(document,{childList:!0,subtree:!0});function s(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function e(r){if(r.ep)return;r.ep=!0;const t=s(r);fetch(r.href,t)}})();const c="46813700-d54068e337851aebc3c875554",l=async n=>{const o=`https://pixabay.com/api/?key=${c}&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true`;try{const s=await fetch(o);if(!s.ok)throw new Error("Network response was not ok");const e=await s.json();return console.log("Fetched data:",e),Array.isArray(e.hits)?e.hits:(console.error("Expected data.hits to be an array:",e.hits),[])}catch(s){throw console.error("Fetch error:",s),s}},d=n=>{const o=document.querySelector(".gallery");if(o.innerHTML="",n.length===0){u("Sorry, there are no images matching your search query. Please try again!");return}const s=n.map(e=>`
        <a href="${e.largeImageURL}">
            <div class="gallery-item">
                <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
                <div class="info">
                    <p>Likes: ${e.likes}</p>
                    <p>Views: ${e.views}</p>
                    <p>Comments: ${e.comments}</p>
                    <p>Downloads: ${e.downloads}</p>
                </div>
            </div>
        </a>
    `).join("");o.insertAdjacentHTML("beforeend",s)},u=n=>{a.error({title:"Error",message:n,position:"topRight"})};document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector(".js-search"),o=document.querySelector(".loader"),s=document.querySelector(".gallery");if(!n){console.error("Форма з класом .js-search не знайдена");return}n.addEventListener("submit",async e=>{e.preventDefault();const r=e.currentTarget.elements.searchQuery.value.trim();if(!r){a.error({title:"Error",message:"Please enter a search query"});return}o.style.display="block",s.innerHTML="";try{const t=await l(r);if(!t||!Array.isArray(t.hits)){a.error({title:"Error",message:"Unexpected response format"});return}t.hits.length===0?a.info({message:"Sorry, there are no images matching your search query. Please try again!"}):d(t.hits)}catch(t){a.error({title:"Error",message:t.message})}finally{o.style.display="none"}})});
//# sourceMappingURL=index.js.map
